/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.22.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.k8s.sparkoperator.v1beta2.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.k8s.sparkoperator.v1beta2.models.V1beta2ScheduledSparkApplicationSpecTemplateProjectedConfigMap;
import io.k8s.sparkoperator.v1beta2.models.V1beta2ScheduledSparkApplicationSpecTemplateProjectedDownwardAPI;
import io.k8s.sparkoperator.v1beta2.models.V1beta2ScheduledSparkApplicationSpecTemplateProjectedServiceAccountToken;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1beta2ScheduledSparkApplicationSpecTemplateProjectedSources
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-05T08:55:35.785Z[Etc/UTC]")
public class V1beta2ScheduledSparkApplicationSpecTemplateProjectedSources {
  public static final String SERIALIZED_NAME_CONFIG_MAP = "configMap";
  @SerializedName(SERIALIZED_NAME_CONFIG_MAP)
  private V1beta2ScheduledSparkApplicationSpecTemplateProjectedConfigMap configMap;

  public static final String SERIALIZED_NAME_DOWNWARD_A_P_I = "downwardAPI";
  @SerializedName(SERIALIZED_NAME_DOWNWARD_A_P_I)
  private V1beta2ScheduledSparkApplicationSpecTemplateProjectedDownwardAPI downwardAPI;

  public static final String SERIALIZED_NAME_SECRET = "secret";
  @SerializedName(SERIALIZED_NAME_SECRET)
  private V1beta2ScheduledSparkApplicationSpecTemplateProjectedConfigMap secret;

  public static final String SERIALIZED_NAME_SERVICE_ACCOUNT_TOKEN = "serviceAccountToken";
  @SerializedName(SERIALIZED_NAME_SERVICE_ACCOUNT_TOKEN)
  private V1beta2ScheduledSparkApplicationSpecTemplateProjectedServiceAccountToken serviceAccountToken;


  public V1beta2ScheduledSparkApplicationSpecTemplateProjectedSources configMap(V1beta2ScheduledSparkApplicationSpecTemplateProjectedConfigMap configMap) {
    
    this.configMap = configMap;
    return this;
  }

   /**
   * Get configMap
   * @return configMap
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta2ScheduledSparkApplicationSpecTemplateProjectedConfigMap getConfigMap() {
    return configMap;
  }


  public void setConfigMap(V1beta2ScheduledSparkApplicationSpecTemplateProjectedConfigMap configMap) {
    this.configMap = configMap;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateProjectedSources downwardAPI(V1beta2ScheduledSparkApplicationSpecTemplateProjectedDownwardAPI downwardAPI) {
    
    this.downwardAPI = downwardAPI;
    return this;
  }

   /**
   * Get downwardAPI
   * @return downwardAPI
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta2ScheduledSparkApplicationSpecTemplateProjectedDownwardAPI getDownwardAPI() {
    return downwardAPI;
  }


  public void setDownwardAPI(V1beta2ScheduledSparkApplicationSpecTemplateProjectedDownwardAPI downwardAPI) {
    this.downwardAPI = downwardAPI;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateProjectedSources secret(V1beta2ScheduledSparkApplicationSpecTemplateProjectedConfigMap secret) {
    
    this.secret = secret;
    return this;
  }

   /**
   * Get secret
   * @return secret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta2ScheduledSparkApplicationSpecTemplateProjectedConfigMap getSecret() {
    return secret;
  }


  public void setSecret(V1beta2ScheduledSparkApplicationSpecTemplateProjectedConfigMap secret) {
    this.secret = secret;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateProjectedSources serviceAccountToken(V1beta2ScheduledSparkApplicationSpecTemplateProjectedServiceAccountToken serviceAccountToken) {
    
    this.serviceAccountToken = serviceAccountToken;
    return this;
  }

   /**
   * Get serviceAccountToken
   * @return serviceAccountToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta2ScheduledSparkApplicationSpecTemplateProjectedServiceAccountToken getServiceAccountToken() {
    return serviceAccountToken;
  }


  public void setServiceAccountToken(V1beta2ScheduledSparkApplicationSpecTemplateProjectedServiceAccountToken serviceAccountToken) {
    this.serviceAccountToken = serviceAccountToken;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta2ScheduledSparkApplicationSpecTemplateProjectedSources v1beta2ScheduledSparkApplicationSpecTemplateProjectedSources = (V1beta2ScheduledSparkApplicationSpecTemplateProjectedSources) o;
    return Objects.equals(this.configMap, v1beta2ScheduledSparkApplicationSpecTemplateProjectedSources.configMap) &&
        Objects.equals(this.downwardAPI, v1beta2ScheduledSparkApplicationSpecTemplateProjectedSources.downwardAPI) &&
        Objects.equals(this.secret, v1beta2ScheduledSparkApplicationSpecTemplateProjectedSources.secret) &&
        Objects.equals(this.serviceAccountToken, v1beta2ScheduledSparkApplicationSpecTemplateProjectedSources.serviceAccountToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(configMap, downwardAPI, secret, serviceAccountToken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta2ScheduledSparkApplicationSpecTemplateProjectedSources {\n");
    sb.append("    configMap: ").append(toIndentedString(configMap)).append("\n");
    sb.append("    downwardAPI: ").append(toIndentedString(downwardAPI)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    serviceAccountToken: ").append(toIndentedString(serviceAccountToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

