/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.22.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.k8s.sparkoperator.v1beta2.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.k8s.sparkoperator.v1beta2.models.V1beta2ScheduledSparkApplicationSpecTemplateMonitoringPrometheus;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1beta2ScheduledSparkApplicationSpecTemplateMonitoring
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-05T08:55:35.785Z[Etc/UTC]")
public class V1beta2ScheduledSparkApplicationSpecTemplateMonitoring {
  public static final String SERIALIZED_NAME_EXPOSE_DRIVER_METRICS = "exposeDriverMetrics";
  @SerializedName(SERIALIZED_NAME_EXPOSE_DRIVER_METRICS)
  private Boolean exposeDriverMetrics;

  public static final String SERIALIZED_NAME_EXPOSE_EXECUTOR_METRICS = "exposeExecutorMetrics";
  @SerializedName(SERIALIZED_NAME_EXPOSE_EXECUTOR_METRICS)
  private Boolean exposeExecutorMetrics;

  public static final String SERIALIZED_NAME_METRICS_PROPERTIES = "metricsProperties";
  @SerializedName(SERIALIZED_NAME_METRICS_PROPERTIES)
  private String metricsProperties;

  public static final String SERIALIZED_NAME_METRICS_PROPERTIES_FILE = "metricsPropertiesFile";
  @SerializedName(SERIALIZED_NAME_METRICS_PROPERTIES_FILE)
  private String metricsPropertiesFile;

  public static final String SERIALIZED_NAME_PROMETHEUS = "prometheus";
  @SerializedName(SERIALIZED_NAME_PROMETHEUS)
  private V1beta2ScheduledSparkApplicationSpecTemplateMonitoringPrometheus prometheus;


  public V1beta2ScheduledSparkApplicationSpecTemplateMonitoring exposeDriverMetrics(Boolean exposeDriverMetrics) {
    
    this.exposeDriverMetrics = exposeDriverMetrics;
    return this;
  }

   /**
   * Get exposeDriverMetrics
   * @return exposeDriverMetrics
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getExposeDriverMetrics() {
    return exposeDriverMetrics;
  }


  public void setExposeDriverMetrics(Boolean exposeDriverMetrics) {
    this.exposeDriverMetrics = exposeDriverMetrics;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateMonitoring exposeExecutorMetrics(Boolean exposeExecutorMetrics) {
    
    this.exposeExecutorMetrics = exposeExecutorMetrics;
    return this;
  }

   /**
   * Get exposeExecutorMetrics
   * @return exposeExecutorMetrics
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getExposeExecutorMetrics() {
    return exposeExecutorMetrics;
  }


  public void setExposeExecutorMetrics(Boolean exposeExecutorMetrics) {
    this.exposeExecutorMetrics = exposeExecutorMetrics;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateMonitoring metricsProperties(String metricsProperties) {
    
    this.metricsProperties = metricsProperties;
    return this;
  }

   /**
   * Get metricsProperties
   * @return metricsProperties
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMetricsProperties() {
    return metricsProperties;
  }


  public void setMetricsProperties(String metricsProperties) {
    this.metricsProperties = metricsProperties;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateMonitoring metricsPropertiesFile(String metricsPropertiesFile) {
    
    this.metricsPropertiesFile = metricsPropertiesFile;
    return this;
  }

   /**
   * Get metricsPropertiesFile
   * @return metricsPropertiesFile
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMetricsPropertiesFile() {
    return metricsPropertiesFile;
  }


  public void setMetricsPropertiesFile(String metricsPropertiesFile) {
    this.metricsPropertiesFile = metricsPropertiesFile;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateMonitoring prometheus(V1beta2ScheduledSparkApplicationSpecTemplateMonitoringPrometheus prometheus) {
    
    this.prometheus = prometheus;
    return this;
  }

   /**
   * Get prometheus
   * @return prometheus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta2ScheduledSparkApplicationSpecTemplateMonitoringPrometheus getPrometheus() {
    return prometheus;
  }


  public void setPrometheus(V1beta2ScheduledSparkApplicationSpecTemplateMonitoringPrometheus prometheus) {
    this.prometheus = prometheus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta2ScheduledSparkApplicationSpecTemplateMonitoring v1beta2ScheduledSparkApplicationSpecTemplateMonitoring = (V1beta2ScheduledSparkApplicationSpecTemplateMonitoring) o;
    return Objects.equals(this.exposeDriverMetrics, v1beta2ScheduledSparkApplicationSpecTemplateMonitoring.exposeDriverMetrics) &&
        Objects.equals(this.exposeExecutorMetrics, v1beta2ScheduledSparkApplicationSpecTemplateMonitoring.exposeExecutorMetrics) &&
        Objects.equals(this.metricsProperties, v1beta2ScheduledSparkApplicationSpecTemplateMonitoring.metricsProperties) &&
        Objects.equals(this.metricsPropertiesFile, v1beta2ScheduledSparkApplicationSpecTemplateMonitoring.metricsPropertiesFile) &&
        Objects.equals(this.prometheus, v1beta2ScheduledSparkApplicationSpecTemplateMonitoring.prometheus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exposeDriverMetrics, exposeExecutorMetrics, metricsProperties, metricsPropertiesFile, prometheus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta2ScheduledSparkApplicationSpecTemplateMonitoring {\n");
    sb.append("    exposeDriverMetrics: ").append(toIndentedString(exposeDriverMetrics)).append("\n");
    sb.append("    exposeExecutorMetrics: ").append(toIndentedString(exposeExecutorMetrics)).append("\n");
    sb.append("    metricsProperties: ").append(toIndentedString(metricsProperties)).append("\n");
    sb.append("    metricsPropertiesFile: ").append(toIndentedString(metricsPropertiesFile)).append("\n");
    sb.append("    prometheus: ").append(toIndentedString(prometheus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

