/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.22.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.k8s.sparkoperator.v1beta2.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.k8s.sparkoperator.v1beta2.models.V1beta2ScheduledSparkApplicationSpecTemplateCephfsSecretRef;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1beta2ScheduledSparkApplicationSpecTemplateIscsi
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-05T08:55:35.785Z[Etc/UTC]")
public class V1beta2ScheduledSparkApplicationSpecTemplateIscsi {
  public static final String SERIALIZED_NAME_CHAP_AUTH_DISCOVERY = "chapAuthDiscovery";
  @SerializedName(SERIALIZED_NAME_CHAP_AUTH_DISCOVERY)
  private Boolean chapAuthDiscovery;

  public static final String SERIALIZED_NAME_CHAP_AUTH_SESSION = "chapAuthSession";
  @SerializedName(SERIALIZED_NAME_CHAP_AUTH_SESSION)
  private Boolean chapAuthSession;

  public static final String SERIALIZED_NAME_FS_TYPE = "fsType";
  @SerializedName(SERIALIZED_NAME_FS_TYPE)
  private String fsType;

  public static final String SERIALIZED_NAME_INITIATOR_NAME = "initiatorName";
  @SerializedName(SERIALIZED_NAME_INITIATOR_NAME)
  private String initiatorName;

  public static final String SERIALIZED_NAME_IQN = "iqn";
  @SerializedName(SERIALIZED_NAME_IQN)
  private String iqn;

  public static final String SERIALIZED_NAME_ISCSI_INTERFACE = "iscsiInterface";
  @SerializedName(SERIALIZED_NAME_ISCSI_INTERFACE)
  private String iscsiInterface;

  public static final String SERIALIZED_NAME_LUN = "lun";
  @SerializedName(SERIALIZED_NAME_LUN)
  private Integer lun;

  public static final String SERIALIZED_NAME_PORTALS = "portals";
  @SerializedName(SERIALIZED_NAME_PORTALS)
  private List<String> portals = null;

  public static final String SERIALIZED_NAME_READ_ONLY = "readOnly";
  @SerializedName(SERIALIZED_NAME_READ_ONLY)
  private Boolean readOnly;

  public static final String SERIALIZED_NAME_SECRET_REF = "secretRef";
  @SerializedName(SERIALIZED_NAME_SECRET_REF)
  private V1beta2ScheduledSparkApplicationSpecTemplateCephfsSecretRef secretRef;

  public static final String SERIALIZED_NAME_TARGET_PORTAL = "targetPortal";
  @SerializedName(SERIALIZED_NAME_TARGET_PORTAL)
  private String targetPortal;


  public V1beta2ScheduledSparkApplicationSpecTemplateIscsi chapAuthDiscovery(Boolean chapAuthDiscovery) {
    
    this.chapAuthDiscovery = chapAuthDiscovery;
    return this;
  }

   /**
   * Get chapAuthDiscovery
   * @return chapAuthDiscovery
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getChapAuthDiscovery() {
    return chapAuthDiscovery;
  }


  public void setChapAuthDiscovery(Boolean chapAuthDiscovery) {
    this.chapAuthDiscovery = chapAuthDiscovery;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateIscsi chapAuthSession(Boolean chapAuthSession) {
    
    this.chapAuthSession = chapAuthSession;
    return this;
  }

   /**
   * Get chapAuthSession
   * @return chapAuthSession
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getChapAuthSession() {
    return chapAuthSession;
  }


  public void setChapAuthSession(Boolean chapAuthSession) {
    this.chapAuthSession = chapAuthSession;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateIscsi fsType(String fsType) {
    
    this.fsType = fsType;
    return this;
  }

   /**
   * Get fsType
   * @return fsType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFsType() {
    return fsType;
  }


  public void setFsType(String fsType) {
    this.fsType = fsType;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateIscsi initiatorName(String initiatorName) {
    
    this.initiatorName = initiatorName;
    return this;
  }

   /**
   * Get initiatorName
   * @return initiatorName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getInitiatorName() {
    return initiatorName;
  }


  public void setInitiatorName(String initiatorName) {
    this.initiatorName = initiatorName;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateIscsi iqn(String iqn) {
    
    this.iqn = iqn;
    return this;
  }

   /**
   * Get iqn
   * @return iqn
  **/
  @ApiModelProperty(required = true, value = "")

  public String getIqn() {
    return iqn;
  }


  public void setIqn(String iqn) {
    this.iqn = iqn;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateIscsi iscsiInterface(String iscsiInterface) {
    
    this.iscsiInterface = iscsiInterface;
    return this;
  }

   /**
   * Get iscsiInterface
   * @return iscsiInterface
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIscsiInterface() {
    return iscsiInterface;
  }


  public void setIscsiInterface(String iscsiInterface) {
    this.iscsiInterface = iscsiInterface;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateIscsi lun(Integer lun) {
    
    this.lun = lun;
    return this;
  }

   /**
   * Get lun
   * @return lun
  **/
  @ApiModelProperty(required = true, value = "")

  public Integer getLun() {
    return lun;
  }


  public void setLun(Integer lun) {
    this.lun = lun;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateIscsi portals(List<String> portals) {
    
    this.portals = portals;
    return this;
  }

  public V1beta2ScheduledSparkApplicationSpecTemplateIscsi addPortalsItem(String portalsItem) {
    if (this.portals == null) {
      this.portals = new ArrayList<>();
    }
    this.portals.add(portalsItem);
    return this;
  }

   /**
   * Get portals
   * @return portals
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getPortals() {
    return portals;
  }


  public void setPortals(List<String> portals) {
    this.portals = portals;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateIscsi readOnly(Boolean readOnly) {
    
    this.readOnly = readOnly;
    return this;
  }

   /**
   * Get readOnly
   * @return readOnly
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getReadOnly() {
    return readOnly;
  }


  public void setReadOnly(Boolean readOnly) {
    this.readOnly = readOnly;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateIscsi secretRef(V1beta2ScheduledSparkApplicationSpecTemplateCephfsSecretRef secretRef) {
    
    this.secretRef = secretRef;
    return this;
  }

   /**
   * Get secretRef
   * @return secretRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta2ScheduledSparkApplicationSpecTemplateCephfsSecretRef getSecretRef() {
    return secretRef;
  }


  public void setSecretRef(V1beta2ScheduledSparkApplicationSpecTemplateCephfsSecretRef secretRef) {
    this.secretRef = secretRef;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateIscsi targetPortal(String targetPortal) {
    
    this.targetPortal = targetPortal;
    return this;
  }

   /**
   * Get targetPortal
   * @return targetPortal
  **/
  @ApiModelProperty(required = true, value = "")

  public String getTargetPortal() {
    return targetPortal;
  }


  public void setTargetPortal(String targetPortal) {
    this.targetPortal = targetPortal;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta2ScheduledSparkApplicationSpecTemplateIscsi v1beta2ScheduledSparkApplicationSpecTemplateIscsi = (V1beta2ScheduledSparkApplicationSpecTemplateIscsi) o;
    return Objects.equals(this.chapAuthDiscovery, v1beta2ScheduledSparkApplicationSpecTemplateIscsi.chapAuthDiscovery) &&
        Objects.equals(this.chapAuthSession, v1beta2ScheduledSparkApplicationSpecTemplateIscsi.chapAuthSession) &&
        Objects.equals(this.fsType, v1beta2ScheduledSparkApplicationSpecTemplateIscsi.fsType) &&
        Objects.equals(this.initiatorName, v1beta2ScheduledSparkApplicationSpecTemplateIscsi.initiatorName) &&
        Objects.equals(this.iqn, v1beta2ScheduledSparkApplicationSpecTemplateIscsi.iqn) &&
        Objects.equals(this.iscsiInterface, v1beta2ScheduledSparkApplicationSpecTemplateIscsi.iscsiInterface) &&
        Objects.equals(this.lun, v1beta2ScheduledSparkApplicationSpecTemplateIscsi.lun) &&
        Objects.equals(this.portals, v1beta2ScheduledSparkApplicationSpecTemplateIscsi.portals) &&
        Objects.equals(this.readOnly, v1beta2ScheduledSparkApplicationSpecTemplateIscsi.readOnly) &&
        Objects.equals(this.secretRef, v1beta2ScheduledSparkApplicationSpecTemplateIscsi.secretRef) &&
        Objects.equals(this.targetPortal, v1beta2ScheduledSparkApplicationSpecTemplateIscsi.targetPortal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chapAuthDiscovery, chapAuthSession, fsType, initiatorName, iqn, iscsiInterface, lun, portals, readOnly, secretRef, targetPortal);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta2ScheduledSparkApplicationSpecTemplateIscsi {\n");
    sb.append("    chapAuthDiscovery: ").append(toIndentedString(chapAuthDiscovery)).append("\n");
    sb.append("    chapAuthSession: ").append(toIndentedString(chapAuthSession)).append("\n");
    sb.append("    fsType: ").append(toIndentedString(fsType)).append("\n");
    sb.append("    initiatorName: ").append(toIndentedString(initiatorName)).append("\n");
    sb.append("    iqn: ").append(toIndentedString(iqn)).append("\n");
    sb.append("    iscsiInterface: ").append(toIndentedString(iscsiInterface)).append("\n");
    sb.append("    lun: ").append(toIndentedString(lun)).append("\n");
    sb.append("    portals: ").append(toIndentedString(portals)).append("\n");
    sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
    sb.append("    secretRef: ").append(toIndentedString(secretRef)).append("\n");
    sb.append("    targetPortal: ").append(toIndentedString(targetPortal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

