/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.22.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.k8s.sparkoperator.v1beta2.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1beta2ScheduledSparkApplicationSpecTemplateDeps
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-05T08:55:35.785Z[Etc/UTC]")
public class V1beta2ScheduledSparkApplicationSpecTemplateDeps {
  public static final String SERIALIZED_NAME_EXCLUDE_PACKAGES = "excludePackages";
  @SerializedName(SERIALIZED_NAME_EXCLUDE_PACKAGES)
  private List<String> excludePackages = null;

  public static final String SERIALIZED_NAME_FILES = "files";
  @SerializedName(SERIALIZED_NAME_FILES)
  private List<String> files = null;

  public static final String SERIALIZED_NAME_JARS = "jars";
  @SerializedName(SERIALIZED_NAME_JARS)
  private List<String> jars = null;

  public static final String SERIALIZED_NAME_PACKAGES = "packages";
  @SerializedName(SERIALIZED_NAME_PACKAGES)
  private List<String> packages = null;

  public static final String SERIALIZED_NAME_PY_FILES = "pyFiles";
  @SerializedName(SERIALIZED_NAME_PY_FILES)
  private List<String> pyFiles = null;

  public static final String SERIALIZED_NAME_REPOSITORIES = "repositories";
  @SerializedName(SERIALIZED_NAME_REPOSITORIES)
  private List<String> repositories = null;


  public V1beta2ScheduledSparkApplicationSpecTemplateDeps excludePackages(List<String> excludePackages) {
    
    this.excludePackages = excludePackages;
    return this;
  }

  public V1beta2ScheduledSparkApplicationSpecTemplateDeps addExcludePackagesItem(String excludePackagesItem) {
    if (this.excludePackages == null) {
      this.excludePackages = new ArrayList<>();
    }
    this.excludePackages.add(excludePackagesItem);
    return this;
  }

   /**
   * Get excludePackages
   * @return excludePackages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getExcludePackages() {
    return excludePackages;
  }


  public void setExcludePackages(List<String> excludePackages) {
    this.excludePackages = excludePackages;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateDeps files(List<String> files) {
    
    this.files = files;
    return this;
  }

  public V1beta2ScheduledSparkApplicationSpecTemplateDeps addFilesItem(String filesItem) {
    if (this.files == null) {
      this.files = new ArrayList<>();
    }
    this.files.add(filesItem);
    return this;
  }

   /**
   * Get files
   * @return files
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getFiles() {
    return files;
  }


  public void setFiles(List<String> files) {
    this.files = files;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateDeps jars(List<String> jars) {
    
    this.jars = jars;
    return this;
  }

  public V1beta2ScheduledSparkApplicationSpecTemplateDeps addJarsItem(String jarsItem) {
    if (this.jars == null) {
      this.jars = new ArrayList<>();
    }
    this.jars.add(jarsItem);
    return this;
  }

   /**
   * Get jars
   * @return jars
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getJars() {
    return jars;
  }


  public void setJars(List<String> jars) {
    this.jars = jars;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateDeps packages(List<String> packages) {
    
    this.packages = packages;
    return this;
  }

  public V1beta2ScheduledSparkApplicationSpecTemplateDeps addPackagesItem(String packagesItem) {
    if (this.packages == null) {
      this.packages = new ArrayList<>();
    }
    this.packages.add(packagesItem);
    return this;
  }

   /**
   * Get packages
   * @return packages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getPackages() {
    return packages;
  }


  public void setPackages(List<String> packages) {
    this.packages = packages;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateDeps pyFiles(List<String> pyFiles) {
    
    this.pyFiles = pyFiles;
    return this;
  }

  public V1beta2ScheduledSparkApplicationSpecTemplateDeps addPyFilesItem(String pyFilesItem) {
    if (this.pyFiles == null) {
      this.pyFiles = new ArrayList<>();
    }
    this.pyFiles.add(pyFilesItem);
    return this;
  }

   /**
   * Get pyFiles
   * @return pyFiles
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getPyFiles() {
    return pyFiles;
  }


  public void setPyFiles(List<String> pyFiles) {
    this.pyFiles = pyFiles;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateDeps repositories(List<String> repositories) {
    
    this.repositories = repositories;
    return this;
  }

  public V1beta2ScheduledSparkApplicationSpecTemplateDeps addRepositoriesItem(String repositoriesItem) {
    if (this.repositories == null) {
      this.repositories = new ArrayList<>();
    }
    this.repositories.add(repositoriesItem);
    return this;
  }

   /**
   * Get repositories
   * @return repositories
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getRepositories() {
    return repositories;
  }


  public void setRepositories(List<String> repositories) {
    this.repositories = repositories;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta2ScheduledSparkApplicationSpecTemplateDeps v1beta2ScheduledSparkApplicationSpecTemplateDeps = (V1beta2ScheduledSparkApplicationSpecTemplateDeps) o;
    return Objects.equals(this.excludePackages, v1beta2ScheduledSparkApplicationSpecTemplateDeps.excludePackages) &&
        Objects.equals(this.files, v1beta2ScheduledSparkApplicationSpecTemplateDeps.files) &&
        Objects.equals(this.jars, v1beta2ScheduledSparkApplicationSpecTemplateDeps.jars) &&
        Objects.equals(this.packages, v1beta2ScheduledSparkApplicationSpecTemplateDeps.packages) &&
        Objects.equals(this.pyFiles, v1beta2ScheduledSparkApplicationSpecTemplateDeps.pyFiles) &&
        Objects.equals(this.repositories, v1beta2ScheduledSparkApplicationSpecTemplateDeps.repositories);
  }

  @Override
  public int hashCode() {
    return Objects.hash(excludePackages, files, jars, packages, pyFiles, repositories);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta2ScheduledSparkApplicationSpecTemplateDeps {\n");
    sb.append("    excludePackages: ").append(toIndentedString(excludePackages)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("    jars: ").append(toIndentedString(jars)).append("\n");
    sb.append("    packages: ").append(toIndentedString(packages)).append("\n");
    sb.append("    pyFiles: ").append(toIndentedString(pyFiles)).append("\n");
    sb.append("    repositories: ").append(toIndentedString(repositories)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

