/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.22.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.k8s.sparkoperator.v1beta2.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1beta2ScheduledSparkApplicationSpecTemplateRestartPolicy
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-05T08:55:35.785Z[Etc/UTC]")
public class V1beta2ScheduledSparkApplicationSpecTemplateRestartPolicy {
  public static final String SERIALIZED_NAME_ON_FAILURE_RETRIES = "onFailureRetries";
  @SerializedName(SERIALIZED_NAME_ON_FAILURE_RETRIES)
  private Integer onFailureRetries;

  public static final String SERIALIZED_NAME_ON_FAILURE_RETRY_INTERVAL = "onFailureRetryInterval";
  @SerializedName(SERIALIZED_NAME_ON_FAILURE_RETRY_INTERVAL)
  private Long onFailureRetryInterval;

  public static final String SERIALIZED_NAME_ON_SUBMISSION_FAILURE_RETRIES = "onSubmissionFailureRetries";
  @SerializedName(SERIALIZED_NAME_ON_SUBMISSION_FAILURE_RETRIES)
  private Integer onSubmissionFailureRetries;

  public static final String SERIALIZED_NAME_ON_SUBMISSION_FAILURE_RETRY_INTERVAL = "onSubmissionFailureRetryInterval";
  @SerializedName(SERIALIZED_NAME_ON_SUBMISSION_FAILURE_RETRY_INTERVAL)
  private Long onSubmissionFailureRetryInterval;

  /**
   * Gets or Sets type
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    NEVER("Never"),
    
    ALWAYS("Always"),
    
    ONFAILURE("OnFailure");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;


  public V1beta2ScheduledSparkApplicationSpecTemplateRestartPolicy onFailureRetries(Integer onFailureRetries) {
    
    this.onFailureRetries = onFailureRetries;
    return this;
  }

   /**
   * Get onFailureRetries
   * minimum: 0
   * @return onFailureRetries
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getOnFailureRetries() {
    return onFailureRetries;
  }


  public void setOnFailureRetries(Integer onFailureRetries) {
    this.onFailureRetries = onFailureRetries;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateRestartPolicy onFailureRetryInterval(Long onFailureRetryInterval) {
    
    this.onFailureRetryInterval = onFailureRetryInterval;
    return this;
  }

   /**
   * Get onFailureRetryInterval
   * minimum: 1
   * @return onFailureRetryInterval
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getOnFailureRetryInterval() {
    return onFailureRetryInterval;
  }


  public void setOnFailureRetryInterval(Long onFailureRetryInterval) {
    this.onFailureRetryInterval = onFailureRetryInterval;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateRestartPolicy onSubmissionFailureRetries(Integer onSubmissionFailureRetries) {
    
    this.onSubmissionFailureRetries = onSubmissionFailureRetries;
    return this;
  }

   /**
   * Get onSubmissionFailureRetries
   * minimum: 0
   * @return onSubmissionFailureRetries
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getOnSubmissionFailureRetries() {
    return onSubmissionFailureRetries;
  }


  public void setOnSubmissionFailureRetries(Integer onSubmissionFailureRetries) {
    this.onSubmissionFailureRetries = onSubmissionFailureRetries;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateRestartPolicy onSubmissionFailureRetryInterval(Long onSubmissionFailureRetryInterval) {
    
    this.onSubmissionFailureRetryInterval = onSubmissionFailureRetryInterval;
    return this;
  }

   /**
   * Get onSubmissionFailureRetryInterval
   * minimum: 1
   * @return onSubmissionFailureRetryInterval
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getOnSubmissionFailureRetryInterval() {
    return onSubmissionFailureRetryInterval;
  }


  public void setOnSubmissionFailureRetryInterval(Long onSubmissionFailureRetryInterval) {
    this.onSubmissionFailureRetryInterval = onSubmissionFailureRetryInterval;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateRestartPolicy type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public TypeEnum getType() {
    return type;
  }


  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta2ScheduledSparkApplicationSpecTemplateRestartPolicy v1beta2ScheduledSparkApplicationSpecTemplateRestartPolicy = (V1beta2ScheduledSparkApplicationSpecTemplateRestartPolicy) o;
    return Objects.equals(this.onFailureRetries, v1beta2ScheduledSparkApplicationSpecTemplateRestartPolicy.onFailureRetries) &&
        Objects.equals(this.onFailureRetryInterval, v1beta2ScheduledSparkApplicationSpecTemplateRestartPolicy.onFailureRetryInterval) &&
        Objects.equals(this.onSubmissionFailureRetries, v1beta2ScheduledSparkApplicationSpecTemplateRestartPolicy.onSubmissionFailureRetries) &&
        Objects.equals(this.onSubmissionFailureRetryInterval, v1beta2ScheduledSparkApplicationSpecTemplateRestartPolicy.onSubmissionFailureRetryInterval) &&
        Objects.equals(this.type, v1beta2ScheduledSparkApplicationSpecTemplateRestartPolicy.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(onFailureRetries, onFailureRetryInterval, onSubmissionFailureRetries, onSubmissionFailureRetryInterval, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta2ScheduledSparkApplicationSpecTemplateRestartPolicy {\n");
    sb.append("    onFailureRetries: ").append(toIndentedString(onFailureRetries)).append("\n");
    sb.append("    onFailureRetryInterval: ").append(toIndentedString(onFailureRetryInterval)).append("\n");
    sb.append("    onSubmissionFailureRetries: ").append(toIndentedString(onSubmissionFailureRetries)).append("\n");
    sb.append("    onSubmissionFailureRetryInterval: ").append(toIndentedString(onSubmissionFailureRetryInterval)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

