/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.22.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.k8s.sparkoperator.v1beta2.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1beta2ScheduledSparkApplicationStatus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-05T08:55:35.785Z[Etc/UTC]")
public class V1beta2ScheduledSparkApplicationStatus {
  public static final String SERIALIZED_NAME_LAST_RUN = "lastRun";
  @SerializedName(SERIALIZED_NAME_LAST_RUN)
  private Object lastRun;

  public static final String SERIALIZED_NAME_LAST_RUN_NAME = "lastRunName";
  @SerializedName(SERIALIZED_NAME_LAST_RUN_NAME)
  private String lastRunName;

  public static final String SERIALIZED_NAME_NEXT_RUN = "nextRun";
  @SerializedName(SERIALIZED_NAME_NEXT_RUN)
  private Object nextRun;

  public static final String SERIALIZED_NAME_PAST_FAILED_RUN_NAMES = "pastFailedRunNames";
  @SerializedName(SERIALIZED_NAME_PAST_FAILED_RUN_NAMES)
  private List<String> pastFailedRunNames = null;

  public static final String SERIALIZED_NAME_PAST_SUCCESSFUL_RUN_NAMES = "pastSuccessfulRunNames";
  @SerializedName(SERIALIZED_NAME_PAST_SUCCESSFUL_RUN_NAMES)
  private List<String> pastSuccessfulRunNames = null;

  public static final String SERIALIZED_NAME_REASON = "reason";
  @SerializedName(SERIALIZED_NAME_REASON)
  private String reason;

  public static final String SERIALIZED_NAME_SCHEDULE_STATE = "scheduleState";
  @SerializedName(SERIALIZED_NAME_SCHEDULE_STATE)
  private String scheduleState;


  public V1beta2ScheduledSparkApplicationStatus lastRun(Object lastRun) {
    
    this.lastRun = lastRun;
    return this;
  }

   /**
   * Get lastRun
   * @return lastRun
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getLastRun() {
    return lastRun;
  }


  public void setLastRun(Object lastRun) {
    this.lastRun = lastRun;
  }


  public V1beta2ScheduledSparkApplicationStatus lastRunName(String lastRunName) {
    
    this.lastRunName = lastRunName;
    return this;
  }

   /**
   * Get lastRunName
   * @return lastRunName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLastRunName() {
    return lastRunName;
  }


  public void setLastRunName(String lastRunName) {
    this.lastRunName = lastRunName;
  }


  public V1beta2ScheduledSparkApplicationStatus nextRun(Object nextRun) {
    
    this.nextRun = nextRun;
    return this;
  }

   /**
   * Get nextRun
   * @return nextRun
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getNextRun() {
    return nextRun;
  }


  public void setNextRun(Object nextRun) {
    this.nextRun = nextRun;
  }


  public V1beta2ScheduledSparkApplicationStatus pastFailedRunNames(List<String> pastFailedRunNames) {
    
    this.pastFailedRunNames = pastFailedRunNames;
    return this;
  }

  public V1beta2ScheduledSparkApplicationStatus addPastFailedRunNamesItem(String pastFailedRunNamesItem) {
    if (this.pastFailedRunNames == null) {
      this.pastFailedRunNames = new ArrayList<>();
    }
    this.pastFailedRunNames.add(pastFailedRunNamesItem);
    return this;
  }

   /**
   * Get pastFailedRunNames
   * @return pastFailedRunNames
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getPastFailedRunNames() {
    return pastFailedRunNames;
  }


  public void setPastFailedRunNames(List<String> pastFailedRunNames) {
    this.pastFailedRunNames = pastFailedRunNames;
  }


  public V1beta2ScheduledSparkApplicationStatus pastSuccessfulRunNames(List<String> pastSuccessfulRunNames) {
    
    this.pastSuccessfulRunNames = pastSuccessfulRunNames;
    return this;
  }

  public V1beta2ScheduledSparkApplicationStatus addPastSuccessfulRunNamesItem(String pastSuccessfulRunNamesItem) {
    if (this.pastSuccessfulRunNames == null) {
      this.pastSuccessfulRunNames = new ArrayList<>();
    }
    this.pastSuccessfulRunNames.add(pastSuccessfulRunNamesItem);
    return this;
  }

   /**
   * Get pastSuccessfulRunNames
   * @return pastSuccessfulRunNames
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getPastSuccessfulRunNames() {
    return pastSuccessfulRunNames;
  }


  public void setPastSuccessfulRunNames(List<String> pastSuccessfulRunNames) {
    this.pastSuccessfulRunNames = pastSuccessfulRunNames;
  }


  public V1beta2ScheduledSparkApplicationStatus reason(String reason) {
    
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getReason() {
    return reason;
  }


  public void setReason(String reason) {
    this.reason = reason;
  }


  public V1beta2ScheduledSparkApplicationStatus scheduleState(String scheduleState) {
    
    this.scheduleState = scheduleState;
    return this;
  }

   /**
   * Get scheduleState
   * @return scheduleState
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getScheduleState() {
    return scheduleState;
  }


  public void setScheduleState(String scheduleState) {
    this.scheduleState = scheduleState;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta2ScheduledSparkApplicationStatus v1beta2ScheduledSparkApplicationStatus = (V1beta2ScheduledSparkApplicationStatus) o;
    return Objects.equals(this.lastRun, v1beta2ScheduledSparkApplicationStatus.lastRun) &&
        Objects.equals(this.lastRunName, v1beta2ScheduledSparkApplicationStatus.lastRunName) &&
        Objects.equals(this.nextRun, v1beta2ScheduledSparkApplicationStatus.nextRun) &&
        Objects.equals(this.pastFailedRunNames, v1beta2ScheduledSparkApplicationStatus.pastFailedRunNames) &&
        Objects.equals(this.pastSuccessfulRunNames, v1beta2ScheduledSparkApplicationStatus.pastSuccessfulRunNames) &&
        Objects.equals(this.reason, v1beta2ScheduledSparkApplicationStatus.reason) &&
        Objects.equals(this.scheduleState, v1beta2ScheduledSparkApplicationStatus.scheduleState);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastRun, lastRunName, nextRun, pastFailedRunNames, pastSuccessfulRunNames, reason, scheduleState);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta2ScheduledSparkApplicationStatus {\n");
    sb.append("    lastRun: ").append(toIndentedString(lastRun)).append("\n");
    sb.append("    lastRunName: ").append(toIndentedString(lastRunName)).append("\n");
    sb.append("    nextRun: ").append(toIndentedString(nextRun)).append("\n");
    sb.append("    pastFailedRunNames: ").append(toIndentedString(pastFailedRunNames)).append("\n");
    sb.append("    pastSuccessfulRunNames: ").append(toIndentedString(pastSuccessfulRunNames)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    scheduleState: ").append(toIndentedString(scheduleState)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

