/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.22.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.k8s.sparkoperator.v1beta2.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.k8s.sparkoperator.v1beta2.models.V1beta2ScheduledSparkApplicationSpecTemplateDriverDnsConfigOptions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1beta2ScheduledSparkApplicationSpecTemplateDriverDnsConfig
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-05T08:55:35.785Z[Etc/UTC]")
public class V1beta2ScheduledSparkApplicationSpecTemplateDriverDnsConfig {
  public static final String SERIALIZED_NAME_NAMESERVERS = "nameservers";
  @SerializedName(SERIALIZED_NAME_NAMESERVERS)
  private List<String> nameservers = null;

  public static final String SERIALIZED_NAME_OPTIONS = "options";
  @SerializedName(SERIALIZED_NAME_OPTIONS)
  private List<V1beta2ScheduledSparkApplicationSpecTemplateDriverDnsConfigOptions> options = null;

  public static final String SERIALIZED_NAME_SEARCHES = "searches";
  @SerializedName(SERIALIZED_NAME_SEARCHES)
  private List<String> searches = null;


  public V1beta2ScheduledSparkApplicationSpecTemplateDriverDnsConfig nameservers(List<String> nameservers) {
    
    this.nameservers = nameservers;
    return this;
  }

  public V1beta2ScheduledSparkApplicationSpecTemplateDriverDnsConfig addNameserversItem(String nameserversItem) {
    if (this.nameservers == null) {
      this.nameservers = new ArrayList<>();
    }
    this.nameservers.add(nameserversItem);
    return this;
  }

   /**
   * Get nameservers
   * @return nameservers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getNameservers() {
    return nameservers;
  }


  public void setNameservers(List<String> nameservers) {
    this.nameservers = nameservers;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateDriverDnsConfig options(List<V1beta2ScheduledSparkApplicationSpecTemplateDriverDnsConfigOptions> options) {
    
    this.options = options;
    return this;
  }

  public V1beta2ScheduledSparkApplicationSpecTemplateDriverDnsConfig addOptionsItem(V1beta2ScheduledSparkApplicationSpecTemplateDriverDnsConfigOptions optionsItem) {
    if (this.options == null) {
      this.options = new ArrayList<>();
    }
    this.options.add(optionsItem);
    return this;
  }

   /**
   * Get options
   * @return options
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1beta2ScheduledSparkApplicationSpecTemplateDriverDnsConfigOptions> getOptions() {
    return options;
  }


  public void setOptions(List<V1beta2ScheduledSparkApplicationSpecTemplateDriverDnsConfigOptions> options) {
    this.options = options;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateDriverDnsConfig searches(List<String> searches) {
    
    this.searches = searches;
    return this;
  }

  public V1beta2ScheduledSparkApplicationSpecTemplateDriverDnsConfig addSearchesItem(String searchesItem) {
    if (this.searches == null) {
      this.searches = new ArrayList<>();
    }
    this.searches.add(searchesItem);
    return this;
  }

   /**
   * Get searches
   * @return searches
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getSearches() {
    return searches;
  }


  public void setSearches(List<String> searches) {
    this.searches = searches;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta2ScheduledSparkApplicationSpecTemplateDriverDnsConfig v1beta2ScheduledSparkApplicationSpecTemplateDriverDnsConfig = (V1beta2ScheduledSparkApplicationSpecTemplateDriverDnsConfig) o;
    return Objects.equals(this.nameservers, v1beta2ScheduledSparkApplicationSpecTemplateDriverDnsConfig.nameservers) &&
        Objects.equals(this.options, v1beta2ScheduledSparkApplicationSpecTemplateDriverDnsConfig.options) &&
        Objects.equals(this.searches, v1beta2ScheduledSparkApplicationSpecTemplateDriverDnsConfig.searches);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nameservers, options, searches);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta2ScheduledSparkApplicationSpecTemplateDriverDnsConfig {\n");
    sb.append("    nameservers: ").append(toIndentedString(nameservers)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    searches: ").append(toIndentedString(searches)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

