/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.22.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.k8s.sparkoperator.v1beta2.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1beta2ScheduledSparkApplicationSpecTemplateMonitoringPrometheus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-04-05T08:55:35.785Z[Etc/UTC]")
public class V1beta2ScheduledSparkApplicationSpecTemplateMonitoringPrometheus {
  public static final String SERIALIZED_NAME_CONFIG_FILE = "configFile";
  @SerializedName(SERIALIZED_NAME_CONFIG_FILE)
  private String configFile;

  public static final String SERIALIZED_NAME_CONFIGURATION = "configuration";
  @SerializedName(SERIALIZED_NAME_CONFIGURATION)
  private String _configuration;

  public static final String SERIALIZED_NAME_JMX_EXPORTER_JAR = "jmxExporterJar";
  @SerializedName(SERIALIZED_NAME_JMX_EXPORTER_JAR)
  private String jmxExporterJar;

  public static final String SERIALIZED_NAME_PORT = "port";
  @SerializedName(SERIALIZED_NAME_PORT)
  private Integer port;

  public static final String SERIALIZED_NAME_PORT_NAME = "portName";
  @SerializedName(SERIALIZED_NAME_PORT_NAME)
  private String portName;


  public V1beta2ScheduledSparkApplicationSpecTemplateMonitoringPrometheus configFile(String configFile) {
    
    this.configFile = configFile;
    return this;
  }

   /**
   * Get configFile
   * @return configFile
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getConfigFile() {
    return configFile;
  }


  public void setConfigFile(String configFile) {
    this.configFile = configFile;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateMonitoringPrometheus _configuration(String _configuration) {
    
    this._configuration = _configuration;
    return this;
  }

   /**
   * Get _configuration
   * @return _configuration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getConfiguration() {
    return _configuration;
  }


  public void setConfiguration(String _configuration) {
    this._configuration = _configuration;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateMonitoringPrometheus jmxExporterJar(String jmxExporterJar) {
    
    this.jmxExporterJar = jmxExporterJar;
    return this;
  }

   /**
   * Get jmxExporterJar
   * @return jmxExporterJar
  **/
  @ApiModelProperty(required = true, value = "")

  public String getJmxExporterJar() {
    return jmxExporterJar;
  }


  public void setJmxExporterJar(String jmxExporterJar) {
    this.jmxExporterJar = jmxExporterJar;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateMonitoringPrometheus port(Integer port) {
    
    this.port = port;
    return this;
  }

   /**
   * Get port
   * minimum: 1024
   * maximum: 49151
   * @return port
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getPort() {
    return port;
  }


  public void setPort(Integer port) {
    this.port = port;
  }


  public V1beta2ScheduledSparkApplicationSpecTemplateMonitoringPrometheus portName(String portName) {
    
    this.portName = portName;
    return this;
  }

   /**
   * Get portName
   * @return portName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPortName() {
    return portName;
  }


  public void setPortName(String portName) {
    this.portName = portName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta2ScheduledSparkApplicationSpecTemplateMonitoringPrometheus v1beta2ScheduledSparkApplicationSpecTemplateMonitoringPrometheus = (V1beta2ScheduledSparkApplicationSpecTemplateMonitoringPrometheus) o;
    return Objects.equals(this.configFile, v1beta2ScheduledSparkApplicationSpecTemplateMonitoringPrometheus.configFile) &&
        Objects.equals(this._configuration, v1beta2ScheduledSparkApplicationSpecTemplateMonitoringPrometheus._configuration) &&
        Objects.equals(this.jmxExporterJar, v1beta2ScheduledSparkApplicationSpecTemplateMonitoringPrometheus.jmxExporterJar) &&
        Objects.equals(this.port, v1beta2ScheduledSparkApplicationSpecTemplateMonitoringPrometheus.port) &&
        Objects.equals(this.portName, v1beta2ScheduledSparkApplicationSpecTemplateMonitoringPrometheus.portName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(configFile, _configuration, jmxExporterJar, port, portName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta2ScheduledSparkApplicationSpecTemplateMonitoringPrometheus {\n");
    sb.append("    configFile: ").append(toIndentedString(configFile)).append("\n");
    sb.append("    _configuration: ").append(toIndentedString(_configuration)).append("\n");
    sb.append("    jmxExporterJar: ").append(toIndentedString(jmxExporterJar)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    portName: ").append(toIndentedString(portName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

